export const foodData = [
    {
        id: 1,
        name: 'apple',
        img: 'apple.png',
        serving: '1 fruit',
        calories: 95,
        protein: .5,
        carbs: 25,
        fat: .3,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 2,
        name: 'banana',
        img: 'banana.png',
        serving: '1 fruit',
        calories: 105,
        protein: 1.3,
        carbs: 27,
        fat: .4,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 3,
        name: 'salmon',
        img: 'salmon.png',
        serving: '1oz',
        calories: 52,
        protein: 7.2,
        carbs: 0,
        fat: 2.3,
        category: 'fish',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 4,
        name: 'asparagus',
        img: 'asparagus.png',
        serving: '1 cup',
        calories: 40,
        protein: 4.3,
        carbs: 7.4,
        fat: .4,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 5,
        name: 'avocado',
        img: 'avocado.png',
        serving: '1 small',
        calories: 227,
        protein: 2.7,
        carbs: 11.8,
        fat: 21,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 6,
        name: 'bacon',
        img: 'bacon.png',
        serving: '1 slice',
        calories: 37,
        protein: 2.7,
        carbs: .1,
        fat: 2.8,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true
    },
    {
        id: 7,
        name: 'crackers',
        img: 'cracker.png',
        serving:'6 crackers',
        calories: 123,
        protein: 2.8,
        carbs: 20.3,
        fat: 4.1,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 8,
        name: 'blueberries',
        img: 'blueberries.png',
        serving: '1 cup',
        calories: 84,
        protein: 1.1,
        carbs: 21.4,
        fat: .5,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 9,
        name: 'wheat bread',
        img: 'bread.png',
        serving: '1 slice',
        calories: 91,
        protein: 4.5,
        carbs: 15.4,
        fat: 1.3,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 10,
        name: 'broccoli',
        img: 'broccoli.png',
        serving: '1 cup',
        calories: 24,
        protein: 2.0,
        carbs: 4.7,
        fat: .3,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 11,
        name: 'carrot',
        img: 'carrot.png',
        serving: '1 medium',
        calories: 25,
        protein: .6,
        carbs: 5.8,
        fat: .1,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 12,
        name: 'cereal',
        img: 'cereal.png',
        serving: '1 cup',
        calories: 105,
        protein: 3.4,
        carbs: 20.5,
        fat: 1.9,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 13,
        name: 'cheese',
        img: 'cheese.png',
        serving: '1oz',
        calories: 114,
        protein: 6.5,
        carbs: 1.0,
        fat: 9.4,
        category: 'dairy',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 14,
        name: 'chips',
        img: 'chips.png',
        serving: '1 cup',
        calories: 133,
        protein: 1.2,
        carbs: 13.5,
        fat: 8.5,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 15,
        name: 'dark chocolate',
        img: 'chocolate.png',
        serving: '1oz',
        calories: 170,
        protein: 2.2,
        carbs: 13.0,
        fat: 12.1,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 16,
        name: 'cookie',
        img: 'cookies.png',
        serving: '1oz',
        calories: 139,
        protein: 1.5,
        carbs: 19.0,
        fat: 6.9,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 17,
        name: 'croissant',
        img: 'croissant.png',
        serving: '1 small',
        calories: 191,
        protein: 3.4,
        carbs: 19.7,
        fat: 11.0,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 18,
        name: 'cupcake',
        img: 'cupcake.png',
        serving: '1 small',
        calories: 174,
        protein: 2.0,
        carbs: 30.3,
        fat: 6.0,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 19,
        name: 'fries',
        img: 'fries.png',
        serving: '1 cup',
        calories: 294,
        protein: 3.3,
        carbs: 38.7,
        fat: 14.6,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 20,
        name: 'grapes',
        img: 'grapes.png',
        serving: '1 cup',
        calories: 104,
        protein: 1.1,
        carbs: 27.3,
        fat: .2,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 21,
        name: 'hamburber',
        img: 'hamburger.png',
        serving: '1 single',
        calories: 492,
        protein: 25.3,
        carbs: 36.4,
        fat: 26.6,
        category: 'meat',
        isVegetarian: false,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 22,
        name: 'chicken',
        img: 'chicken.png',
        serving: '1oz',
        calories: 49,
        protein: 8.8,
        carbs: 0,
        fat: 1.3,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 23,
        name: 'lamb',
        img: 'lamb.png',
        serving: '1oz',
        calories: 78,
        protein: 6.4,
        carbs: 0,
        fat: 5.7,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 24,
        name: 'mushrooms',
        img: 'mushrooms.png',
        serving: '1 cup',
        calories: 21,
        protein: 3.0,
        carbs: 3.1,
        fat: .3,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 25,
        name: 'olives',
        img: 'olives.png',
        serving: '1oz',
        calories: 41,
        protein: .3,
        carbs: 1.1,
        fat: 4.3,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 26,
        name: 'orange',
        img: 'orange.png',
        serving: '1 medium',
        calories: 62,
        protein: 1.2,
        carbs: 15.4,
        fat: .2,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 27,
        name: 'pasta',
        img: 'pasta.png',
        serving: '1 cup',
        calories: 168,
        protein: 6.2,
        carbs: 32.7,
        fat: 1.0,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 28,
        name: 'pineapple',
        img: 'pineapple.png',
        serving: '1 cup',
        calories: 83,
        protein: .9,
        carbs: 21.6,
        fat: .2,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 29,
        name: 'pizza',
        img: 'pizza.png',
        serving: '1 slice',
        calories: 320,
        protein: 15.0,
        carbs: 40.0,
        fat: 9.0,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 30,
        name: 'potato',
        img: 'potato.png',
        serving: '1 meduim',
        calories: 161,
        protein: 4.3,
        carbs: 35.5,
        fat: .2,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 31,
        name: 'pretzels',
        img: 'pretzel.png',
        serving: '1oz',
        calories: 111,
        protein: 3.0,
        carbs: 22.6,
        fat: .8,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 32,
        name: 'turkey',
        img: 'turkey.png',
        serving: '1oz',
        calories: 42,
        protein: 8.5,
        carbs: 0,
        fat: .6,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 33,
        name: 'rice',
        img: 'rice.png',
        serving: '1 cup',
        calories: 205,
        protein: 4.3,
        carbs: 44.5,
        fat: .4,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 34,
        name: 'lettuce',
        img: 'lettuce.png',
        serving: '1 cup',
        calories: 8,
        protein: .6,
        carbs: 1.5,
        fat: .1,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 35,
        name: 'strawberry',
        img: 'strawberry.png',
        serving: '1 cup',
        calories: 49,
        protein: 1.0,
        carbs: 11.7,
        fat: .5,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 36,
        name: 'sushi',
        img: 'sushi.png',
        serving: '1 roll',
        calories: 350,
        protein: 19.0,
        carbs: 41.0,
        fat: 12.0,
        category: 'meat',
        isVegetarian: false,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 37,
        name: 'taco',
        img: 'taco.png',
        serving: '1 crunchy',
        calories: 170,
        protein: 8.0,
        carbs: 13.0,
        fat: 9.0,
        category: 'meat',
        isVegetarian: false,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 38,
        name: 'tomato',
        img: 'tomato.png',
        serving: '1 medium',
        calories: 22,
        protein: 1.1,
        carbs: 4.8,
        fat: 0.2,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 39,
        name: 'watermelon',
        img: 'watermelon.png',
        serving: '1 cup',
        calories: 30,
        protein: .6,
        carbs: 7.4,
        fat: 0.1,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 40,
        name: 'salami',
        img: 'salami.png',
        serving: '1oz',
        calories: 101,
        protein: 8.1,
        carbs: 0,
        fat: 8.1,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 41,
        name: 'pistachio',
        img: 'pistachio.png',
        serving: '1oz',
        calories: 161,
        protein: 6.0,
        carbs: 7.8,
        fat: 13.0,
        category: 'snack',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 42,
        name: 'peas',
        img: 'peas.png',
        serving: '1 cup',
        calories: 125,
        protein: 8.2,
        carbs: 22.8,
        fat: 0.4,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 43,
        name: 'olive oil',
        img: 'oil.png',
        serving: '1 tbsp',
        calories: 119,
        protein: 0,
        carbs: 0,
        fat: 13.5,
        category: 'other',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 44,
        name: 'popsicle',
        img: 'popsicle.png',
        serving: '1 each',
        calories: 41,
        protein: 0,
        carbs: 10.0,
        fat: .1,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 45,
        name: 'ice cream',
        img: 'icecream.png',
        serving: '1 cup',
        calories: 273,
        protein: 4.6,
        carbs: 31.2,
        fat: 14.5,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 46,
        name: 'bean burger',
        img: 'beanburger.png',
        serving: '1 patty',
        calories: 130,
        protein: 6.0,
        carbs: 18.5,
        fat: 4.1,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 47,
        name: 'steak',
        img: 'steak.png',
        serving: '1oz',
        calories: 45,
        protein: 8.5,
        carbs: 0,
        fat: 1.3,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 48,
        name: 'egg',
        img: 'egg.png',
        serving: '1 medium',
        calories: 68,
        protein: 5.5,
        carbs: .5,
        fat: 4.7,
        category: 'dairy',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 49,
        name: 'doughnut',
        img: 'doughnut.png',
        serving: '1 medium',
        calories: 330,
        protein: 4.4,
        carbs: 39.3,
        fat: 17.4,
        category: 'snack',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 50,
        name: 'fish',
        img: 'fish.png',
        serving: '1oz',
        calories: 41,
        protein: 6.6,
        carbs: 0,
        fat: 1.4,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 51,
        name: 'beans',
        img: 'beans.png',
        serving: '1oz',
        calories: 40,
        protein: 2.3,
        carbs: 7.4,
        fat: 0.2,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 52,
        name: 'cabbage',
        img: 'cabbage.png',
        serving: '1 cup',
        calories: 33,
        protein: 1.7,
        carbs: 7.6,
        fat: 0.1,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 53,
        name: 'corn',
        img: 'corn.png',
        serving: '1 cup',
        calories: 134,
        protein: 4.2,
        carbs: 31.8,
        fat: 1.1,
        category: 'vegetable',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: true,
    },
    {
        id: 54,
        name: 'oat',
        img: 'oat.png',
        serving: '1oz',
        calories: 107,
        protein: 3.7,
        carbs: 19.2,
        fat: 1.8,
        category: 'grain',
        isVegetarian: true,
        isPaleo: false,
        isGlutenFree: false,
    },
    {
        id: 55,
        name: 'raspberries',
        img: 'raspberries.png',
        serving: '1 cup',
        calories: 64,
        protein: 1.5,
        carbs: 14.7,
        fat: 0.8,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 56,
        name: 'shrimp',
        img: 'shrimp.png',
        serving: '1oz ',
        calories: 34,
        protein: 6.5,
        carbs: .4,
        fat: 0.5,
        category: 'meat',
        isVegetarian: false,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 57,
        name: 'coconut',
        img: 'coconut.png',
        serving: '1oz ',
        calories: 100,
        protein: .9,
        carbs: 4.3,
        fat: 9.5,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    {
        id: 58,
        name: 'cherries',
        img: 'cherries.png',
        serving: '1 cup',
        calories: 97,
        protein: 1.6,
        carbs: 24.7,
        fat: .3,
        category: 'fruit',
        isVegetarian: true,
        isPaleo: true,
        isGlutenFree: true,
    },
    
];

export const instructions = [{
    name: 'homePage',
    description: 'You\'re well on your way to managing a healthy and personalized diet plan. The first step is to tell Nutri a little about yourself. Nutri likes to know the name of their friends, their goal caloric intake and any dietary restrictions.',
},
{
    name: 'foodPageMain',
    description: 'Here is where you will tell Nutri what foods it was you\'ve ate today.'
},
{
    name: 'food-log',
    description: 'Congratulations on adding some foods to your list, here is a breakdown of the foods you\'ve eaten today! You can edit your list on this page.'
},
{
    name: 'resultsPage',
    description: 'Congratulations on filling out you diet log!'
}];

export const team = [{
    name: 'Patrick Hrabos',
    img: 'patrick.png',
    img2: 'patrick2.jpeg',
    description: 'The badass son of a gun coding up our responsive reliable table datas',
    linkedIn: '<a href=\'https://www.linkedin.com/in/patrick-hrabos/\'><img src="../assets/linkedin.png"  class="meeds"/></a>',
    github: '<a href=\'https://www.github.com/phrabos\'><img src="../assets/github.png"  class="meeds"/></a>',
}, 
{
    name: 'Minh Ngo',
    img: 'minh.png',
    img2: 'minh2.jpeg',
    description: 'The badass son of a gun coding up our responsive reliable table datas',
    linkedIn: '<a href=\'https://www.linkedin.com/in/minhnngo/\'><img src="../assets/linkedin.png"  class="meeds"/></a>',
    github: '<a href=\'https://www.github.com/ngominh0224\'><img src="../assets/github.png"  class="meeds"/></a>',   
}, {
    name: 'Jake Thrasher',
    img: 'jake.png',
    img2: 'jake2.jpeg',
    description: 'The badass son of a gun coding up our responsive reliable table datas',
    linkedIn: '<a href=\'https://www.linkedin.com/in/m-jake-thrasher/\'><img src="../assets/linkedin.png"  class="meeds"/></a>',
    github: '<a href=\'https://www.github.com/jakethrasher\'><img src="../assets/github.png"  class="meeds"/></a>',
}, {
    name: 'Dom Sakrisson',
    img: 'dom.png',
    img2: 'dom2.jpeg',
    description: 'The badass son of a gun coding up our responsive reliable table datas',
    linkedIn: '<a href="https://www.linkedin.com/in/dominique-sakrisson/"><img src="../assets/linkedin.png" class="meeds" /></a>',
    github: '<a href="https://www.github.com/Dominique-Sakrisson"><img src="../assets/github.png"  class="meeds" /></a>',
}];